# Window configuration
[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }
decorations = "Full"
opacity = 0.98  # Slight transparency (0.0 = fully transparent, 1.0 = opaque)
blur = true
title = ""
# Font configuration
[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 14.0

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[colors.hints]
start = { foreground = "#ffffff", background = "#ff6b6b" }

end = { foreground = "#ffffff", background = "#ff6b6b" }

[mouse]
hide_when_typing = false

[cursor]
thickness=0.01

[hints]
alphabet = "jfkdls;ahgurieowpq"

# Edit text files (Command + E)
[[hints.enabled]]
regex = "[^\\s]+\\.(py|sh|md)"
command = "nvim"
binding = { key = "E", mods = "Command" }

# Open media files and URLs (Command + O)
[[hints.enabled]]
regex = "[^\\s]+\\.(jpg|jpeg|png|gif|bmp|svg)|https?://[^\\s]+"
command = "open"
binding = { key = "O", mods = "Command" }
hyperlinks = true
post_processing = true

# Copy file paths and URLs (Command + C)
[[hints.enabled]]
regex = "[^\\s]+\\.(py|sh|md|jpg|jpeg|png|gif|bmp|svg)|https?://[^\\s]+"
action = "Copy"
binding = { key = "C", mods = "Command" }

# Run Python scripts (Command + P)
[[hints.enabled]]
regex = "[^\\s]+\\.py"
command = "python"
binding = { key = "P", mods = "Command" }

# Key bindings
[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"  # CTRL+U, which erases the entire line in most shells

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bb"  # ALT+B, which moves back one word in most shells

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bf"  # ALT+F, which moves forward one word in most shellsi

# New key binding to open a new window
[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

# Other settings
[scrolling]
history = 10000

[selection]
save_to_clipboard = true
